server:
  port: 8081

dubbo:
  application:
    ##### 注册服务的名称
    name: consumer
  ##### 注册中心地址
  registry:
    address: zookeeper://192.168.126.129:2181
  ##### 调用服务超时时间
  consumer:
    timeout: 5000

spring:
  output:
    ansi:
      enabled: always